/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package luoyong.dinnerpanel.android;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int food_list_selector=0x7f050000;
    }
    public static final class drawable {
        public static final int cold_dish=0x7f020000;
        public static final int hot_dish=0x7f020001;
        public static final int pasta_conchiglie=0x7f020002;
        public static final int pasta_farfalle=0x7f020003;
        public static final int pasta_macaroni=0x7f020004;
        public static final int pasta_mostaciolli=0x7f020005;
        public static final int pasta_rotini=0x7f020006;
        public static final int pasta_spahetti=0x7f020007;
        public static final int pasta_ziti=0x7f020008;
        public static final int soup=0x7f020009;
        public static final int staple_food=0x7f02000a;
    }
    public static final class id {
        public static final int confirm_dialog_main_view=0x7f060000;
        public static final int confirm_dialog_view_comment=0x7f060002;
        public static final int confirm_dialog_view_food_count=0x7f060001;
        public static final int food_category_view_button=0x7f060005;
        public static final int food_category_view_grid=0x7f060004;
        public static final int food_list_view_button_add=0x7f060007;
        public static final int food_list_view_button_back=0x7f060008;
        public static final int food_list_view_gallery=0x7f060006;
        public static final int main_view=0x7f060003;
    }
    public static final class layout {
        public static final int confirm_dialog_layout=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
